{application,broadway_dashboard,
             [{modules,['Elixir.BroadwayDashboard',
                        'Elixir.BroadwayDashboard.Application',
                        'Elixir.BroadwayDashboard.Counters',
                        'Elixir.BroadwayDashboard.Metrics',
                        'Elixir.BroadwayDashboard.PipelineGraph',
                        'Elixir.BroadwayDashboard.Telemetry',
                        'Elixir.BroadwayDashboard.Teleporter']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,broadway,
                             phoenix_live_dashboard]},
              {description,"A Phoenix LiveDashboard page for inspecting your Broadway pipelines"},
              {registered,[]},
              {vsn,"0.4.1"},
              {mod,{'Elixir.BroadwayDashboard.Application',[]}}]}.
